// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package registry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Environment int32

const (
	Environment_Development Environment = 0
	Environment_Production  Environment = 1
)

var Environment_name = map[int32]string{
	0: "Development",
	1: "Production",
}

var Environment_value = map[string]int32{
	"Development": 0,
	"Production":  1,
}

func (x Environment) String() string {
	return proto.EnumName(Environment_name, int32(x))
}

func (Environment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Service struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Env                  Environment `protobuf:"varint,2,opt,name=env,proto3,enum=registry.Environment" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetEnv() Environment {
	if m != nil {
		return m.Env
	}
	return Environment_Development
}

type Connection struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connection) Reset()         { *m = Connection{} }
func (m *Connection) String() string { return proto.CompactTextString(m) }
func (*Connection) ProtoMessage()    {}
func (*Connection) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *Connection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connection.Unmarshal(m, b)
}
func (m *Connection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connection.Marshal(b, m, deterministic)
}
func (m *Connection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connection.Merge(m, src)
}
func (m *Connection) XXX_Size() int {
	return xxx_messageInfo_Connection.Size(m)
}
func (m *Connection) XXX_DiscardUnknown() {
	xxx_messageInfo_Connection.DiscardUnknown(m)
}

var xxx_messageInfo_Connection proto.InternalMessageInfo

func (m *Connection) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegistrationForm struct {
	Service              *Service    `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Connection           *Connection `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegistrationForm) Reset()         { *m = RegistrationForm{} }
func (m *RegistrationForm) String() string { return proto.CompactTextString(m) }
func (*RegistrationForm) ProtoMessage()    {}
func (*RegistrationForm) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{3}
}

func (m *RegistrationForm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationForm.Unmarshal(m, b)
}
func (m *RegistrationForm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationForm.Marshal(b, m, deterministic)
}
func (m *RegistrationForm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationForm.Merge(m, src)
}
func (m *RegistrationForm) XXX_Size() int {
	return xxx_messageInfo_RegistrationForm.Size(m)
}
func (m *RegistrationForm) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationForm.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationForm proto.InternalMessageInfo

func (m *RegistrationForm) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *RegistrationForm) GetConnection() *Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func init() {
	proto.RegisterEnum("registry.Environment", Environment_name, Environment_value)
	proto.RegisterType((*Empty)(nil), "registry.Empty")
	proto.RegisterType((*Service)(nil), "registry.Service")
	proto.RegisterType((*Connection)(nil), "registry.Connection")
	proto.RegisterType((*RegistrationForm)(nil), "registry.RegistrationForm")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0x85, 0x40,
	0x10, 0x87, 0xb5, 0x7f, 0x9e, 0x46, 0x50, 0x1b, 0x0a, 0xc4, 0xab, 0xc3, 0x5e, 0xd4, 0xa1, 0xc0,
	0x0b, 0x0b, 0xba, 0x0d, 0xea, 0x9c, 0x6e, 0x63, 0x7b, 0x02, 0xd3, 0x21, 0x84, 0xdc, 0x95, 0x75,
	0x8f, 0xe0, 0x03, 0xf4, 0xde, 0xe1, 0xea, 0x1e, 0xa5, 0xba, 0x9b, 0x81, 0x6f, 0x67, 0xbe, 0xf9,
	0x2d, 0x04, 0x8a, 0x3e, 0xab, 0x56, 0xab, 0x3e, 0x6d, 0x94, 0xd4, 0x12, 0x57, 0xb6, 0x67, 0x1e,
	0x9c, 0x6e, 0xeb, 0x46, 0xf7, 0x6c, 0x07, 0xde, 0x3b, 0xa9, 0xae, 0x2a, 0x08, 0x11, 0x4e, 0x44,
	0x5e, 0x53, 0xec, 0xae, 0xdd, 0xcd, 0x39, 0x37, 0x35, 0xde, 0xc0, 0x31, 0x89, 0x2e, 0x3e, 0x5a,
	0xbb, 0x9b, 0x20, 0xbb, 0x4a, 0x0f, 0xf3, 0xb6, 0xa2, 0xab, 0x94, 0x14, 0x35, 0x09, 0xcd, 0x07,
	0x82, 0x5d, 0x03, 0x3c, 0x4b, 0x21, 0xa8, 0xd0, 0x95, 0x14, 0x18, 0x83, 0x97, 0x97, 0xa5, 0xa2,
	0xb6, 0x9d, 0xa6, 0xd9, 0x96, 0xed, 0x21, 0xe2, 0xe3, 0x90, 0x7c, 0x20, 0x77, 0x52, 0xd5, 0x78,
	0x07, 0x5e, 0x3b, 0x3a, 0x18, 0xda, 0xcf, 0x2e, 0xe6, 0x45, 0x93, 0x1c, 0xb7, 0x04, 0x3e, 0x00,
	0x14, 0x87, 0x45, 0x46, 0xcc, 0xcf, 0x2e, 0x67, 0x7e, 0x96, 0xe0, 0x0b, 0xee, 0x36, 0x05, 0x7f,
	0xa1, 0x8c, 0x21, 0xf8, 0x2f, 0xd4, 0xd1, 0x97, 0x6c, 0x86, 0x36, 0x72, 0x30, 0x00, 0x78, 0x53,
	0xb2, 0xdc, 0x1b, 0x3a, 0x72, 0xb3, 0x6f, 0x17, 0x56, 0x93, 0x67, 0x8f, 0x4f, 0x10, 0x8e, 0x35,
	0x29, 0x9b, 0x55, 0x32, 0x6f, 0xfc, 0x7d, 0x4e, 0x12, 0x2e, 0x62, 0x32, 0x19, 0x3b, 0xf8, 0x08,
	0xf0, 0x4a, 0xda, 0x3e, 0xfe, 0x7b, 0x5e, 0xf2, 0xef, 0x05, 0xcc, 0xf9, 0x38, 0x33, 0x1f, 0x77,
	0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x16, 0x71, 0x83, 0x62, 0xca, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryClient interface {
	RegisterService(ctx context.Context, in *RegistrationForm, opts ...grpc.CallOption) (*Empty, error)
	GetService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Connection, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) RegisterService(ctx context.Context, in *RegistrationForm, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/registry.Registry/RegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Connection, error) {
	out := new(Connection)
	err := c.cc.Invoke(ctx, "/registry.Registry/GetService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
type RegistryServer interface {
	RegisterService(context.Context, *RegistrationForm) (*Empty, error)
	GetService(context.Context, *Service) (*Connection, error)
}

// UnimplementedRegistryServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (*UnimplementedRegistryServer) RegisterService(ctx context.Context, req *RegistrationForm) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (*UnimplementedRegistryServer) GetService(ctx context.Context, req *Service) (*Connection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationForm)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterService(ctx, req.(*RegistrationForm))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registry.Registry/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registry.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _Registry_RegisterService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _Registry_GetService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
